// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "1eb5ced6-e6b7-487e-b1f2-8d3661ce87e1";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onManualButtonChange();
void onOnOffFanChange();
void onOnOffPumpChange();

CloudTemperatureSensor humidity_1;
CloudTemperatureSensor suhu_1;
bool manualButton;
bool onOff_Fan;
bool onOff_Pump;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(humidity_1, READ, ON_CHANGE, NULL, 1);
  ArduinoCloud.addProperty(suhu_1, READ, ON_CHANGE, NULL, 1);
  ArduinoCloud.addProperty(manualButton, READWRITE, ON_CHANGE, onManualButtonChange);
  ArduinoCloud.addProperty(onOff_Fan, READWRITE, ON_CHANGE, onOnOffFanChange);
  ArduinoCloud.addProperty(onOff_Pump, READWRITE, ON_CHANGE, onOnOffPumpChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
